### ISSUE TITLE
SSH Login Menu, Error

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#167]
In the ssh login menu, after running a lab setup option, ie `mlag` after prompted to hit `Enter` to continue, the screen refreshes. 

However, after scrolling up you can see there was an error that occurred in `ConfigureTopology.py` but was able to continue.

Even though the error occurs, you are still able to continue on with other commands, maybe since that portion of the script resides in `ConfigureTopology.py`? Since it exits out `login.py` is able to continue.

```
*****************************************
*****Jump Host for Arista Test Drive*****
*****************************************


==========Main Menu==========

Please select from the following options:
1. Reset All Devices to Base ATD (reset)
2. MLAG Lab (mlag)
3. BGP Lab (bgp)
4. VXLAN Lab (vxlan) excludes leaf3 instead of leaf4
5. EVPN Type 2 Lab (l2evpn) excludes leaf3 instead of leaf4
6. EVPN Type 5 Lab (l3evpn) excludes leaf3 instead of leaf4
7. CVP lab (cvp)


97. Additional Labs (labs)
98. SSH to Devices (ssh)
99. Exit LabVM (quit/exit) - CTRL + c

What would you like to do?: mlag
Please wait while the mlag lab is prepared...
Gathering task information...
Waiting on change control to finish executing...
Lab Setup Completed. Please press Enter to continue...
Traceback (most recent call last):
  File "/usr/local/bin/ConfigureTopology.py", line 209, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/ConfigureTopology.py", line 199, in main
    input("Lab Setup Completed. Please press Enter to continue...")
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing


*****************************************
*****Jump Host for Arista Test Drive*****
*****************************************


==========Main Menu==========

Please select from the following options:
1. Reset All Devices to Base ATD (reset)
2. MLAG Lab (mlag)
3. BGP Lab (bgp)
4. VXLAN Lab (vxlan) excludes leaf3 instead of leaf4
5. EVPN Type 2 Lab (l2evpn) excludes leaf3 instead of leaf4
6. EVPN Type 5 Lab (l3evpn) excludes leaf3 instead of leaf4
7. CVP lab (cvp)


97. Additional Labs (labs)
98. SSH to Devices (ssh)
99. Exit LabVM (quit/exit) - CTRL + c

What would you like to do?:
```

**Comment by networkRob** [comment]
Fixed in #169
