### ISSUE TITLE
gitConfigletSync.py errors in RATD topology

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#79]
The gitConfigletsync.py service is failing with the following error message.  It is only failing in the Routing topology, it is successful in the Datacenter topo.

```
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]: Local copy exists....continuing
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]: Traceback (most recent call last):
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:   File "/usr/local/bin/gitConfigletSync.py", line 84, in <module>
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:     syncConfiglet(clnt,configletName,configletConfig)
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:   File "/usr/local/bin/gitConfigletSync.py", line 64, in syncConfiglet
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:     addConfiglet = cvpClient.api.add_configlet(configletName,configletConfig)
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:   File "/usr/local/lib/python2.7/dist-packages/cvprac/cvp_api.py", line 672, in add_configlet
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:     timeout=self.request_timeout)
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:   File "/usr/local/lib/python2.7/dist-packages/cvprac/cvp_client.py", line 700, in post
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:     return self._make_request('POST', url, timeout, data=data, files=files)
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:   File "/usr/local/lib/python2.7/dist-packages/cvprac/cvp_client.py", line 478, in _make_request
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]:     raise error
Oct 22 18:09:11 ip-10-33-4-164 gitConfigletSync.py[3859]: cvprac.cvp_client_errors.CvpApiError: POST: https://192.168.0.5:443/web/configlet/addConfiglet.do : Request Error: Data already exists in Database
```

**Comment by brokenpackets** [comment]
Probably should add a `check if exists` function first. 
if exist:
    updateConfiglet
else:
    addConfiglet

**Comment by networkRob** [comment]
it's an issue with one configlet that is not pulling the key when it is in the db.

**Comment by networkRob** [comment]
Issue is due to cvpUpdater.py and gitConfigletSync.py performing API calls around the same time.  Need to add requirement for gitConfigletSync.py to start after cvpUpdater.py has completed
